pub mod car_handlers;
pub mod customer_handlers;
pub mod purchase_handlers;
pub mod part_handlers;
pub mod brand_handlers;
pub mod car_model_handlers;
pub mod work_handlers;
pub mod service_campaign_handlers;
pub mod warehouse_handler;

pub use car_handlers::*;
pub use customer_handlers::*;
pub use purchase_handlers::*;
pub use part_handlers::*;
pub use brand_handlers::*;
pub use car_model_handlers::*;
pub use work_handlers::*;
pub use service_campaign_handlers::*;
pub use warehouse_handler::*;