pub mod car;
pub mod customer;
pub mod purchase;
pub mod part;
pub mod brand;
pub mod car_model;
pub mod work;
pub mod enums;
mod service_campaigns;
pub mod warehouse;

pub use car::{Car, CreateCarRequest, UpdateCarRequest};
pub use customer::{Customer, CreateCustomerRequest};
pub use purchase::{PurchaseRequest, CreatePurchaseRequest};
pub use part::{Part, CreatePartRequest, UpdatePartRequest};
pub use brand::{Brand, CreateBrandRequest, UpdateBrandRequest};
pub use car_model::{CarModel, CreateCarModelRequest, UpdateCarModelRequest};
pub use enums::{FuelType, Transmission, CarStatus, RequestStatus};
pub use work::{Work, CreateWorkRequest, UpdateWorkRequest};
pub use service_campaigns::{ServiceCampaign, ServiceCampaignStatus, UpdateServiceCampaignRequest, CreateServiceCampaignRequest};